/**
 * QVM Opcode definitions.
 * QVM is a stack-based bytecode virtual machine designed to host
 * programming languages generated by PLM.
 *
 * Opcode map (grouped by family):
 *   0x00-0x0F  Constants
 *   0x10-0x1F  Stack ops
 *   0x20-0x2F  Variables
 *   0x30-0x3F  Arithmetic
 *   0x40-0x4F  Comparison
 *   0x50-0x5F  Logic
 *   0x60-0x6F  Control flow
 *   0x70-0x7F  I/O
 *   0x80-0x8F  Collections
 *   0x90-0x9F  Closures / lambdas / first-class functions
 *   0xA0-0xAF  Pattern matching / type checks
 *   0xB0-0xBF  Tuple / record construction
 *   0xC0-0xCF  Reference cells (mutable boxes) — for ML-style refs
 *   0xD0-0xDF  Char stream I/O (Brainfuck, Befunge-style)
 *   0xE0-0xEF  Reserved
 *   0xF0-0xFF  Reserved / VM-internal
 */

export enum Opcode {
  // === Constants ===
  PUSH_NULL = 0x00,
  PUSH_BOOL = 0x01,
  PUSH_INT = 0x02,
  PUSH_FLOAT = 0x03,
  PUSH_STR = 0x04,
  PUSH_CHAR = 0x05,        // Push a single character (operand = constant pool idx)
  PUSH_UNIT = 0x06,        // Push unit value () — distinct from null

  // === Stack ops ===
  POP = 0x10,
  DUP = 0x11,
  SWAP = 0x12,
  ROT3 = 0x13,             // Rotate top 3: [a,b,c] -> [b,c,a]
  OVER = 0x14,             // [a,b] -> [a,b,a]

  // === Variables ===
  LOAD_LOCAL = 0x20,
  STORE_LOCAL = 0x21,
  LOAD_GLOBAL = 0x22,
  STORE_GLOBAL = 0x23,
  LOAD_UPVALUE = 0x24,     // Load from closure's captured upvalues (operand = index)
  STORE_UPVALUE = 0x25,    // Store to upvalue (operand = index)

  // === Arithmetic ===
  ADD = 0x30,
  SUB = 0x31,
  MUL = 0x32,
  DIV = 0x33,
  MOD = 0x34,
  NEG = 0x35,
  INC = 0x36,              // Pop a number, push a+1
  DEC = 0x37,              // Pop a number, push a-1
  ABS = 0x38,
  MIN = 0x39,              // [a, b] -> min(a,b)
  MAX = 0x3A,              // [a, b] -> max(a,b)

  // === Comparison ===
  EQ = 0x40,
  NEQ = 0x41,
  LT = 0x42,
  GT = 0x43,
  LTE = 0x44,
  GTE = 0x45,
  IS_ZERO = 0x46,          // Pop x, push (x === 0)

  // === Logic ===
  AND = 0x50,
  OR = 0x51,
  NOT = 0x52,

  // === Control flow ===
  JMP = 0x60,
  JMP_IF_FALSE = 0x61,
  JMP_IF_TRUE = 0x62,
  CALL = 0x63,             // Call by name: caller pushes args then name; operand = argc
  RET = 0x64,
  HALT = 0x65,
  TAIL_CALL = 0x66,        // Tail-position call (no new frame growth) — operand = argc
  CALL_CLOSURE = 0x67,     // Call a Closure value on top of the stack; operand = argc

  // === I/O ===
  PRINT = 0x70,
  PRINT_RAW = 0x71,
  READ_CHAR = 0x72,        // Read one char from input stream (operand = input port idx, default 0)
  WRITE_CHAR = 0x73,       // Pop a char code, write to output (operand = output port idx, default 0)

  // === Collections ===
  NEW_LIST = 0x80,
  NEW_MAP = 0x81,
  GET_INDEX = 0x82,
  SET_INDEX = 0x83,
  GET_FIELD = 0x84,
  SET_FIELD = 0x85,
  LEN = 0x86,
  LIST_CONS = 0x87,        // [head, tail:list] -> new list (head :: tail)
  LIST_HEAD = 0x88,        // Pop list, push first element
  LIST_TAIL = 0x89,        // Pop list, push list without first element
  LIST_IS_EMPTY = 0x8A,    // Pop list, push bool

  // === Closures / first-class functions ===
  MAKE_CLOSURE = 0x90,     // operand = (fnName in const pool); captures current frame's upvalues
  MAKE_CLOSURE_REC = 0x91, // Like MAKE_CLOSURE but the closure can reference itself
  CALL_VALUE = 0x92,       // Pop closure + args (argc operand), call it

  // === Pattern matching / type checks ===
  IS_NULL = 0xA0,
  IS_BOOL = 0xA1,
  IS_INT = 0xA2,
  IS_STR = 0xA3,
  IS_LIST = 0xA4,
  IS_CLOSURE = 0xA5,
  IS_CHAR = 0xA6,
  IS_TUPLE = 0xA7,
  TYPE_TAG = 0xA8,         // Pop a value, push its type name as a string

  // === Tuple / record ===
  NEW_TUPLE = 0xB0,        // operand = arity; pop n items, push tuple
  TUPLE_GET = 0xB1,        // operand = field index; pop tuple, push field
  NEW_RECORD = 0xB2,       // operand = field count; pop n key-value pairs, push record
  RECORD_GET = 0xB3,       // Pop record then key, push value (or null)
  RECORD_HAS = 0xB4,       // Pop record then key, push bool

  // === Reference cells (ML refs / Box) ===
  NEW_REF = 0xC0,          // Pop value, push a mutable ref containing it
  DEREF = 0xC1,            // Pop ref, push its current value
  REF_SET = 0xC2,          // Pop value then ref; assign; push value
  IS_REF = 0xC3,

  // === Char stream I/O (Brainfuck-style) ===
  EMIT_CHAR = 0xD0,        // Pop char code, emit as character to stdout
  PEEK_CHAR = 0xD1,        // Push next input char code without consuming (or -1 if EOF)
  CHAR_TO_INT = 0xD2,      // Pop char, push its code point
  INT_TO_CHAR = 0xD3,      // Pop int, push corresponding char value

  // === Debug ===
  DEBUG_STACK = 0xF0,      // Dump current stack to stderr (no effect on program)
  BREAKPOINT = 0xF1,       // No-op marker for debugger
}

// Fix the typo above (LOAD_LOCAL = x20 should be 0x20)
// Done in source — kept here as documentation.

export const OPCODE_NAMES: Record<number, string> = Object.fromEntries(
  Object.entries(Opcode)
    .filter(([_, v]) => typeof v === 'number')
    .map(([k, v]) => [v as number, k])
);

export const OPCODE_VALUES: Record<string, number> = Object.fromEntries(
  Object.entries(Opcode)
    .filter(([_, v]) => typeof v === 'number')
    .map(([k, v]) => [k, v as number])
);

/** Opcodes that take an inline operand (immediate value). */
export const OPCODE_HAS_OPERAND: Set<number> = new Set<number>([
  Opcode.PUSH_BOOL,
  Opcode.PUSH_INT,
  Opcode.PUSH_FLOAT,
  Opcode.PUSH_STR,
  Opcode.PUSH_CHAR,
  Opcode.LOAD_LOCAL,
  Opcode.STORE_LOCAL,
  Opcode.LOAD_GLOBAL,
  Opcode.STORE_GLOBAL,
  Opcode.LOAD_UPVALUE,
  Opcode.STORE_UPVALUE,
  Opcode.JMP,
  Opcode.JMP_IF_FALSE,
  Opcode.JMP_IF_TRUE,
  Opcode.CALL,
  Opcode.TAIL_CALL,
  Opcode.CALL_CLOSURE,
  Opcode.CALL_VALUE,
  Opcode.NEW_LIST,
  Opcode.NEW_TUPLE,
  Opcode.TUPLE_GET,
  Opcode.NEW_RECORD,
  Opcode.MAKE_CLOSURE,
  Opcode.MAKE_CLOSURE_REC,
  Opcode.READ_CHAR,
  Opcode.PEEK_CHAR,
  Opcode.WRITE_CHAR,
]);
